name: Basic compilation test

on:
  [push, pull_request]

jobs:

  test_builds:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-16.04, ubuntu-latest, ubuntu-20.04]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Ant
        run: |
          make
