name: Docker Image CI

on:
  push:
    branches: [ better_perl_and_tests ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: "ialarmedalien/kb-sdk"
          TAG_NAME: "better_perl_and_tests"
          LATEST: "true"
