name: Docker Image CI

on:
  [push, pull_request]

jobs:
  dockerhub_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: "ialarmedalien/kb-sdk"
          TAG_NAME: "better_perl_and_tests"
          LATEST: "true"

  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Add bin to $PATH
        run: |
          env
          echo "::add-path::$GITHUB_WORKSPACE/bin"
      - name: Build with Ant
        run: |
          make
          make sdkbase
          env
      - name: checking kb-sdk functions
        env:
          KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
        run: |
          kb-sdk help
          kb-sdk init -l python -u sychan --example MyContigFilter
          kb-sdk init -l perl -u user --example PerlExample
          kb-sdk init -l perl -u user PerlBase
          cd PerlExample
          kb-sdk test
          cd ../PerlBase
          kb-sdk test
          cd ../MyContigFilter
          make
          kb-sdk test
