name: Docker Image CI

on:
  push:
    branches: [ better_perl_and_tests ]

jobs:

  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Add bin to $PATH
        run: |
          env
          echo "::add-path::$GITHUB_WORKSPACE/bin"
      - name: Build with Ant
        run: |
          make
          make sdkbase
          env
      - name: checking kb-sdk functions
        env:
          KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
        run: |
          kb-sdk help
          kb-sdk init -l perl -u user PerlBase
          cd PerlBase
          kb-sdk test
          cd ..
          rm -rf PerlBase
          kb-sdk init -l perl -u user --example PerlExample
          cd PerlExample
          kb-sdk test
          cd ..
          rm -rf PerlExample
          kb-sdk init -l python -u user --example MyContigFilter
          cd MyContigFilter
          make
          kb-sdk test
          cd ..
      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: "ialarmedalien/kb-sdk"
          TAG_NAME: "better_perl_and_tests"
          LATEST: "true"
