name: Basic kb-sdk tests

on:
  [push, pull_request]

jobs:

  kb_sdk_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Add bin to $PATH
        run: |
          echo "::add-path::$GITHUB_WORKSPACE/bin"

      - name: Build with Ant
        run: |
          make
          env

      - name: Upload kb-sdk build
        uses: actions/upload-artifact@v2
        with:
          name: kb-sdk_build
          path: bin/kb-sdk

      - name: checking kb-sdk functions
        env:
          KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
        run: |
          kb-sdk help
          kb-sdk version
          kb-sdk init -l perl -u user PerlBase
          cd PerlBase
          kb-sdk test
          cd ..
          rm -rf PerlBase
          kb-sdk init -l perl -u user --example PerlExample
          cd PerlExample
          kb-sdk test
          cd ..
          rm -rf PerlExample
          kb-sdk init -l python -u user --example PythonExample
          cd PythonExample
          make
          kb-sdk test
          cd ..
          rm -rf PythonExample
          kb-sdk init -l java -u user --example JavaExample
          cd JavaExample
          kb-sdk test
