name: Basic kb-sdk tests

on:
  [push, pull_request]

jobs:

  test_builds:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-latest]
#        os: [macos-latest, windows-latest, ubuntu-16.04, ubuntu-latest]
        language: [java, perl, python]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Add bin to $PATH
        run: |
          echo "::add-path::$GITHUB_WORKSPACE/bin"

      - name: Build with Ant
        run: |
          make

      - name: checking kb-sdk functions
        env:
          KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
          LANGUAGE_TOKEN: ${{ matrix.language }}
        run: |
          kb-sdk help
          kb-sdk version
          kb-sdk init -l $LANGUAGE_TOKEN -u user BaseApp
          cd BaseApp
          kb-sdk test
          cd ..
          kb-sdk init -l $LANGUAGE_TOKEN -u user --example ExampleApp
          cd ExampleApp
          kb-sdk test


