name: Basic kb-sdk tests

on:
  [push, pull_request]

jobs:

  test_kb-sdk_builds:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-16.04, ubuntu-latest, ubuntu-20.04]
        language: [perl, python]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Ant
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install ant
          brew install docker

      - name: Build with Ant
        run: |
          make

      - name: Add bin to $PATH
        run: |
          echo "::add-path::$GITHUB_WORKSPACE/bin"

      - name: checking kb-sdk functions
        env:
          KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
          LANGUAGE_TOKEN: ${{ matrix.language }}
        run: |
          kb-sdk help
          kb-sdk version
      - name: init and test base repo
        env:
          KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
          LANGUAGE_TOKEN: ${{ matrix.language }}
        run: |
          kb-sdk init -l $LANGUAGE_TOKEN -u user BaseApp
          cd BaseApp
          kb-sdk test
          cd ..
      - name: init and test example repo
        env:
          KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
          LANGUAGE_TOKEN: ${{ matrix.language }}
        run: |
          kb-sdk init -l $LANGUAGE_TOKEN -u user --example ExampleApp
          cd ExampleApp
          kb-sdk test

  test_java_repos:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-16.04, ubuntu-latest, ubuntu-20.04]
        app: [HTMLFileSetServ, WsLargeDataIO]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Ant
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install ant
          brew install docker

      - name: Build with Ant
        run: |
          make

      - name: Add bin to $PATH
        run: |
          echo "::add-path::$GITHUB_WORKSPACE/bin"

      - name: checking basic kb-sdk functions
        run: |
          env
          kb-sdk help
          kb-sdk version

      - name: init and test Java base repo
        env:
          KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
        run: |
          kb-sdk init -l java -u user BaseApp
          cd BaseApp
          kb-sdk validate || true
          make build-test-script
          sed -i "s/test_token=/test_token=$KBASE_TEST_TOKEN/" test_local/test.cfg
          kb-sdk test
          cd ..

      - name: init and test Java example repo
        env:
          KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
        run: |
          kb-sdk init -l java -u user --example ExampleApp
          cd ExampleApp
          kb-sdk validate || true
          make build-test-script
          sed -i "s/test_token=/test_token=$KBASE_TEST_TOKEN/" test_local/test.cfg
          kb-sdk test

      - name: Checkout existing kbase modules and run tests
        uses: actions/checkout@v2
        with:
          repository: kbaseapps/${{ matrix.app }}
          path: kbase_app

      - name: run repo tests
        env:
          KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
        run: |
          cd kbase_app
          kb-sdk test || true
          make build-test-script
          sed -i "s/test_token=/test_token=$KBASE_TEST_TOKEN/" test_local/test.cfg
          kb-sdk test
          cd ..
