name: Basic kb-sdk tests

on:
  [push, pull_request]

jobs:

  kb_sdk_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Add bin to $PATH
        run: |
          echo "::add-path::$GITHUB_WORKSPACE/bin"

      - name: Build with Ant
        run: |
          make

      - name: Upload kb-sdk build
        uses: actions/upload-artifact@v2
        with:
          name: kb-sdk_build
          path: bin/kb-sdk

      - name: checking kb-sdk functions
        env:
          KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
          LANGUAGE_TOKEN:
          IS_EXAMPLE:
        run: |
          kb-sdk help
          kb-sdk version

  test_builds:
    needs: kb_sdk_build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-16.04, ubuntu-latest]
        language: [java, perl, python]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Add bin to $PATH
        run: |
          echo "::add-path::$GITHUB_WORKSPACE/bin"

      - name: Download kb-sdk build
        uses: actions/download-artifact@v2
        with:
          name: kb-sdk_build
          path: bin/kb-sdk

      - name: Display structure of downloaded files
        run: ls -R

      - name: checking kb-sdk functions
        env:
          KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
          LANGUAGE_TOKEN: ${{ matrix.language }}
        run: |
          kb-sdk help
          kb-sdk version
          kb-sdk init -l $LANGUAGE_TOKEN BaseApp
          cd BaseApp
          kb-sdk test
          cd ..
          kb-sdk init -l $LANGUAGE_TOKEN --example ExampleApp
          cd ExampleApp
          kb-sdk test


